CREATE TABLE IF NOT EXISTS genres (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS musicians (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL, 
);
CREATE TABLE IF NOT EXISTS genre_musician (
	id SERIAL PRIMARY KEY,
	genre_id INTEGER NOT NULL REFERENCES genres(id),
	musician_id INTEGER NOT NULL REFERENCES musicians(id)
);
CREATE TABLE IF NOT EXISTS albums (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL, 
	year INTEGER
);
CREATE TABLE IF NOT EXISTS musician_album (
	id SERIAL PRIMARY KEY,
	musician_id INTEGER NOT NULL REFERENCES musicians(id)
	album_id INTEGER NOT NULL REFERENCES albums(id)
);
CREATE TABLE IF NOT EXISTS tracks (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL, 
	time INTEGER, 
	album_id INTEGER NOT NULL REFERENCES albums(id)
);
CREATE TABLE IF NOT EXISTS mixtapes (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL, 
	year INTEGER
);
CREATE TABLE IF NOT EXISTS mixtape_track (
	id SERIAL PRIMARY KEY,
	mixtape_id INTEGER NOT NULL REFERENCES mixtapes(id)
	track_id INTEGER NOT NULL REFERENCES tracks(id)
);





