CREATE TABLE IF NOT EXISTS genre (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS musicians (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL, 
	id_genre INTEGER REFERENCES genre(id) NOT NULL
);
CREATE TABLE IF NOT EXISTS albums (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL, 
	id_musician INTEGER REFERENCES musicians(id) NOT NULL
);
CREATE TABLE IF NOT EXISTS tracks (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(40) NOT NULL, 
	time TIME, 
	id_album INTEGER REFERENCES albums(id) NOT NULL
);